version: '3.8'
services:
  # Base de datos como servicio, no instalaci√≥n manual
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agprueba
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  authorization-server:
    build: ./authorization-server
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/agprueba
    depends_on:
      mysqldb:
        condition: service_healthy

  resource-server:
    build: ./resource-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/agprueba
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://authorization-server:9000
    depends_on:
      - authorization-server

  frontend:
    build: ./ag-prueba-front
    ports:
      - "4200:80"
